name: Deploy PWA(Preview)

on:
  push:
    branches: [ master ]

  workflow_dispatch:

env:
  DIST_TAG: preview

jobs:
  BuildAndDeploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'

      - name: Install libs
        run: sudo apt install -y libusb-1.0-0-dev libudev-dev

      - name: Install Dependencies
        run: npm ci --legacy-peer-deps --ignore-scripts

      - name: Build Application
        run: npx quasar build -m pwa
        env:
          NODE_OPTIONS: --openssl-legacy-provider

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.ADDTIONAL_GITHUB_TOKEN }}
          publish_dir: dist/pwa
          external_repository: vechain/lite.sync.vecha.in
          cname: lite.sync.vecha.in
          force_orphan: true
